
Things I did in this code

1. READ THE DATA

2. Replaced "na" values with "np.nan" values
3. dropped columns which had more NaN values than decided threshold

4. Filled the rest of missing values using __*SimpleImputer*__ from sklearn

5. Then did the quantization of column values using __*pd.qcut*__ 

6. After that I did __*one-hot encoding*__ of column values

7. applied PCA

7. Then I applied __*SMOTE*__ to balance the dataset

8. Then I did the data splitting

9. Applied Gaussian Naive Bayes algorithm on training dataset

10. Predicted the labels using CV data and calculated the accuracy

# READ THE DATA

In [1]:
import pandas as pd
import numpy as np

train_data = pd.read_csv("aps_failure_training_set.csv", skiprows=20)

test_data = pd.read_csv("aps_failure_test_set.csv",skiprows=20)

In [2]:
data = pd.concat([train_data,test_data])

# Replacing "na" values with "np.nan" values

In [3]:
data.replace(to_replace="na", value = np.nan,inplace=True)

In [4]:
data

class  aa_000 ab_000      ac_000 ad_000 ae_000 af_000 ag_000 ag_001  \
0       neg   76698    NaN  2130706438    280      0      0      0      0   
1       neg   33058    NaN           0    NaN      0      0      0      0   
2       neg   41040    NaN         228    100      0      0      0      0   
3       neg      12      0          70     66      0     10      0      0   
4       neg   60874    NaN        1368    458      0      0      0      0   
...     ...     ...    ...         ...    ...    ...    ...    ...    ...   
15995   neg   81852    NaN  2130706432    892      0      0      0      0   
15996   neg      18      0          52     46      8     26      0      0   
15997   neg   79636    NaN        1670   1518      0      0      0      0   
15998   neg     110    NaN          36     32      0      0      0      0   
15999   neg       8      0           6      4      2      2      0      0   

      ag_002  ...   ee_002  ee_003  ee_004  ee_005  ee_006  ee_007  ee_008  \
0          0  ...  1240520  493384  721044  469792  339156  157956   73224   
1          0  ...   421400  178064  293306  245416  133654   81140   97576   
2          0  ...   277378  159812  423992  409564  320746  158022   95128   
3          0  ...      240      46      58      44      10       0       0   
4          0  ...   622012  229790  405298  347188  286954  311560  433954   
...      ...  ...      ...     ...     ...     ...     ...     ...     ...   
15995      0  ...   632658  273242  510354  373918  349840  317840  960024   
15996      0  ...      266      44      46      14       2       0       0   
15997      0  ...   806832  449962  778826  581558  375498  222866  358934   
15998      0  ...      588     210     180     544    1004    1338      74   
15999      0  ...       46      10      48      14      42      46       0   

      ee_009 ef_000 eg_000  
0          0      0      0  
1       1500      0      0  
2        514      0      0  
3          0      4     32  
4       1218      0      0  
...      ...    ...    ...  
15995  25566      0      0  
15996      0      0      0  
15997  19548      0      0  
15998      0      0      0  
15999      0      0      0  

[76000 rows x 171 columns]

# dropping columns which had more NaN values than decided threshold

In [5]:
data.dropna(axis=1,inplace=True,thresh=(0.8*data.shape[0]))

In [6]:
data

class  aa_000      ac_000 ae_000 af_000 ag_000 ag_001 ag_002 ag_003  \
0       neg   76698  2130706438      0      0      0      0      0      0   
1       neg   33058           0      0      0      0      0      0      0   
2       neg   41040         228      0      0      0      0      0      0   
3       neg      12          70      0     10      0      0      0    318   
4       neg   60874        1368      0      0      0      0      0      0   
...     ...     ...         ...    ...    ...    ...    ...    ...    ...   
15995   neg   81852  2130706432      0      0      0      0      0      0   
15996   neg      18          52      8     26      0      0      0      0   
15997   neg   79636        1670      0      0      0      0      0      0   
15998   neg     110          36      0      0      0      0      0      0   
15999   neg       8           6      2      2      0      0      0      0   

      ag_004  ...   ee_002  ee_003  ee_004  ee_005  ee_006  ee_007  ee_008  \
0      37250  ...  1240520  493384  721044  469792  339156  157956   73224   
1      18254  ...   421400  178064  293306  245416  133654   81140   97576   
2       1648  ...   277378  159812  423992  409564  320746  158022   95128   
3       2212  ...      240      46      58      44      10       0       0   
4      43752  ...   622012  229790  405298  347188  286954  311560  433954   
...      ...  ...      ...     ...     ...     ...     ...     ...     ...   
15995   5486  ...   632658  273242  510354  373918  349840  317840  960024   
15996   6444  ...      266      44      46      14       2       0       0   
15997  15062  ...   806832  449962  778826  581558  375498  222866  358934   
15998    198  ...      588     210     180     544    1004    1338      74   
15999   1350  ...       46      10      48      14      42      46       0   

      ee_009 ef_000 eg_000  
0          0      0      0  
1       1500      0      0  
2        514      0      0  
3          0      4     32  
4       1218      0      0  
...      ...    ...    ...  
15995  25566      0      0  
15996      0      0      0  
15997  19548      0      0  
15998      0      0      0  
15999      0      0      0  

[76000 rows x 147 columns]

# Filling the rest of missing values using __*SimpleImputer*__ from sklearn

In [7]:
from sklearn.impute import SimpleImputer

In [8]:
imputer = SimpleImputer()

In [9]:
data_array = imputer.fit_transform(X=data.iloc[:,1:])

In [10]:
data_array

array([[7.66980000e+04, 2.13070644e+09, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.30580000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        1.50000000e+03, 0.00000000e+00, 0.00000000e+00],
       [4.10400000e+04, 2.28000000e+02, 0.00000000e+00, ...,
        5.14000000e+02, 0.00000000e+00, 0.00000000e+00],
       ...,
       [7.96360000e+04, 1.67000000e+03, 0.00000000e+00, ...,
        1.95480000e+04, 0.00000000e+00, 0.00000000e+00],
       [1.10000000e+02, 3.60000000e+01, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.00000000e+00, 6.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [11]:
data_columns = data.columns
data_labels = data['class']

In [12]:
data = pd.DataFrame(data=data_array,columns=data_columns[1:])

In [13]:
data

aa_000        ac_000  ae_000  af_000  ag_000  ag_001  ag_002  ag_003  \
0      76698.0  2.130706e+09     0.0     0.0     0.0     0.0     0.0     0.0   
1      33058.0  0.000000e+00     0.0     0.0     0.0     0.0     0.0     0.0   
2      41040.0  2.280000e+02     0.0     0.0     0.0     0.0     0.0     0.0   
3         12.0  7.000000e+01     0.0    10.0     0.0     0.0     0.0   318.0   
4      60874.0  1.368000e+03     0.0     0.0     0.0     0.0     0.0     0.0   
...        ...           ...     ...     ...     ...     ...     ...     ...   
75995  81852.0  2.130706e+09     0.0     0.0     0.0     0.0     0.0     0.0   
75996     18.0  5.200000e+01     8.0    26.0     0.0     0.0     0.0     0.0   
75997  79636.0  1.670000e+03     0.0     0.0     0.0     0.0     0.0     0.0   
75998    110.0  3.600000e+01     0.0     0.0     0.0     0.0     0.0     0.0   
75999      8.0  6.000000e+00     2.0     2.0     0.0     0.0     0.0     0.0   

        ag_004     ag_005  ...     ee_002    ee_003    ee_004    ee_005  \
0      37250.0  1432864.0  ...  1240520.0  493384.0  721044.0  469792.0   
1      18254.0   653294.0  ...   421400.0  178064.0  293306.0  245416.0   
2       1648.0   370592.0  ...   277378.0  159812.0  423992.0  409564.0   
3       2212.0     3232.0  ...      240.0      46.0      58.0      44.0   
4      43752.0  1966618.0  ...   622012.0  229790.0  405298.0  347188.0   
...        ...        ...  ...        ...       ...       ...       ...   
75995   5486.0   704012.0  ...   632658.0  273242.0  510354.0  373918.0   
75996   6444.0     3308.0  ...      266.0      44.0      46.0      14.0   
75997  15062.0  1991298.0  ...   806832.0  449962.0  778826.0  581558.0   
75998    198.0     3730.0  ...      588.0     210.0     180.0     544.0   
75999   1350.0     3328.0  ...       46.0      10.0      48.0      14.0   

         ee_006    ee_007    ee_008   ee_009  ef_000  eg_000  
0      339156.0  157956.0   73224.0      0.0     0.0     0.0  
1      133654.0   81140.0   97576.0   1500.0     0.0     0.0  
2      320746.0  158022.0   95128.0    514.0     0.0     0.0  
3          10.0       0.0       0.0      0.0     4.0    32.0  
4      286954.0  311560.0  433954.0   1218.0     0.0     0.0  
...         ...       ...       ...      ...     ...     ...  
75995  349840.0  317840.0  960024.0  25566.0     0.0     0.0  
75996       2.0       0.0       0.0      0.0     0.0     0.0  
75997  375498.0  222866.0  358934.0  19548.0     0.0     0.0  
75998    1004.0    1338.0      74.0      0.0     0.0     0.0  
75999      42.0      46.0       0.0      0.0     0.0     0.0  

[76000 rows x 146 columns]

# Now let's do the quantization of column values using __*pd.qcut*__ 

we can do the binning of these kind of values (quantiles are bins)

In [14]:
unique_values = dict()
for column in data.columns:
    unique_values[column] = len(data[column].unique())

In [15]:
# unique_values

In [16]:
data.drop(['cd_000'],axis=1,inplace=True)     # as cd_000 has only single value so we are gonna drop it

In [17]:
for column in data.columns[0:145]:
    data[column] = pd.qcut(x=data[column],q=5,duplicates='drop').cat.codes

In [18]:
data

aa_000  ac_000  ae_000  af_000  ag_000  ag_001  ag_002  ag_003  ag_004  \
0           4       4       0       0       0       0       0       0       3   
1           2       0       0       0       0       0       0       0       3   
2           3       2       0       0       0       0       0       0       2   
3           0       1       0       0       0       0       0       1       2   
4           4       3       0       0       0       0       0       0       3   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
75995       4       4       0       0       0       0       0       0       2   
75996       0       1       0       0       0       0       0       0       2   
75997       4       3       0       0       0       0       0       0       3   
75998       0       1       0       0       0       0       0       0       1   
75999       0       0       0       0       0       0       0       0       1   

       ag_005  ...  ee_002  ee_003  ee_004  ee_005  ee_006  ee_007  ee_008  \
0           4  ...       4       4       4       3       4       3       2   
1           3  ...       3       3       2       2       2       2       2   
2           2  ...       2       3       3       3       3       3       2   
3           0  ...       0       0       0       0       0       0       0   
4           4  ...       4       3       3       3       3       4       3   
...       ...  ...     ...     ...     ...     ...     ...     ...     ...   
75995       3  ...       4       4       3       3       4       4       3   
75996       0  ...       0       0       0       0       0       0       0   
75997       4  ...       4       4       4       4       4       4       3   
75998       0  ...       0       0       0       0       1       1       0   
75999       0  ...       0       0       0       0       0       1       0   

       ee_009  ef_000  eg_000  
0           0       0       0  
1           1       0       0  
2           1       0       0  
3           0       0       0  
4           1       0       0  
...       ...     ...     ...  
75995       2       0       0  
75996       0       0       0  
75997       2       0       0  
75998       0       0       0  
75999       0       0       0  

[76000 rows x 145 columns]

# Now doing the __*one-hot encoding*__ of column values

In [19]:
np_array_list = list()
for column in data.columns[0:data.shape[1]-1]:
    np_array_list.append(np.eye(10,10)[data[column]])
data_array = np.concatenate(np_array_list,axis=1)

In [20]:
data_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [21]:
data_array.shape

(76000, 1440)

# let's apply dimensionality reduction

In [22]:
from sklearn.decomposition import PCA

In [23]:
pca_obj = PCA(n_components=10)

In [24]:
reduced_data_array = pca_obj.fit_transform(data_array)

In [25]:
reduced_data_array.shape

(76000, 10)

In [26]:
data_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [27]:
reduced_data_array

array([[-3.89134766,  4.20292288,  2.26194903, ..., -0.38273175,
         0.09491248, -0.27210912],
       [-3.22380854, -0.57652535, -1.39948116, ..., -0.52844495,
         1.52530722,  1.79840876],
       [-2.68315602, -3.33444734, -2.8556751 , ...,  1.06247899,
        -2.84072707,  0.26898007],
       ...,
       [-4.12502188,  3.66760517,  1.83414115, ..., -0.13800253,
        -0.58152863, -1.27944563],
       [ 4.99443836, -0.42758154,  1.2913615 , ...,  0.78707815,
         0.90806587, -0.93292751],
       [ 5.99401737,  3.1341563 , -3.56624829, ...,  0.07838696,
         0.15714048,  0.16172464]])

# Let's do data splitting

In [28]:
train_data_len = int(0.8*train_data.shape[0])
train_data_len

48000

In [29]:
cv_data_len = int(0.2*train_data.shape[0])
cv_data_len

12000

In [30]:
test_data_len = test_data.shape[0]
test_data_len

16000

In [31]:
train_data_array = reduced_data_array[0:train_data_len,:]

cv_data_array = reduced_data_array[train_data_len:train_data_len+cv_data_len,:]

test_data_array = reduced_data_array[train_data_len+cv_data_len:,:]

In [32]:
train_data_array.shape

(48000, 10)

In [33]:
cv_data_array.shape

(12000, 10)

In [34]:
test_data_array.shape

(16000, 10)

In [35]:
train_data_array

array([[-3.89134766,  4.20292288,  2.26194903, ..., -0.38273175,
         0.09491248, -0.27210912],
       [-3.22380854, -0.57652535, -1.39948116, ..., -0.52844495,
         1.52530722,  1.79840876],
       [-2.68315602, -3.33444734, -2.8556751 , ...,  1.06247899,
        -2.84072707,  0.26898007],
       ...,
       [ 3.59673191, -2.30003238,  3.6698066 , ..., -0.81078207,
        -0.55266842,  0.82328717],
       [-2.60757196, -3.00159629, -2.30763775, ..., -0.34675061,
         1.73670817, -0.0493462 ],
       [ 5.46551139,  0.99401157, -0.53520082, ..., -1.59583724,
        -0.63817759, -0.52136329]])

# Let's apply smote on training dataset

In [36]:
train_data_new = train_data.iloc[0:train_data_len,:]

In [37]:
train_data_new.shape

(48000, 171)

In [38]:
train_data['class']

0        neg
1        neg
2        neg
3        neg
4        neg
        ... 
59995    neg
59996    neg
59997    neg
59998    neg
59999    neg
Name: class, Length: 60000, dtype: object

In [39]:
from imblearn.over_sampling import SMOTE

In [40]:
smote_obj = SMOTE(sampling_strategy='minority',k_neighbors=5)

In [41]:
X_oversampled, Y_oversampled = smote_obj.fit_resample(X=train_data_array,y=train_data_new['class'])

In [42]:
X_oversampled.shape

(94358, 10)

In [43]:
train_data_new = pd.DataFrame(X_oversampled)
train_data_new['class'] = Y_oversampled

In [44]:
train_data_new

0         1         2         3         4         5         6  \
0     -3.891348  4.202923  2.261949 -0.315250 -2.496029 -0.287258 -0.953096   
1     -3.223809 -0.576525 -1.399481 -1.741053  1.565625  2.502355 -0.946820   
2     -2.683156 -3.334447 -2.855675 -0.489875 -0.265897 -0.612213 -0.282877   
3      5.885344  3.133361 -3.223138  0.453874  0.613880 -0.512425 -0.684405   
4     -3.575372  1.000515  0.037761 -1.827900  0.470906 -0.744885 -1.003587   
...         ...       ...       ...       ...       ...       ...       ...   
94353 -4.331966  5.548651  3.351599  1.216708 -1.076067  0.417629 -1.161209   
94354 -4.322739  4.556372  3.064653  1.963620  1.798829 -0.310259  1.929028   
94355 -4.151473  5.338575  3.128800  1.365733 -1.180791  2.262986 -1.404485   
94356 -4.722029  5.358215  3.443235  2.031392  1.683322 -0.157786  1.777398   
94357 -4.477170  5.144905  3.005460  0.335144 -1.748793 -1.572192 -0.737856   

              7         8         9 class  
0     -0.382732  0.094912 -0.272109   neg  
1     -0.528445  1.525307  1.798409   neg  
2      1.062479 -2.840727  0.268980   neg  
3      0.309898  0.013619 -0.079487   neg  
4     -1.428721 -1.508756 -0.984040   neg  
...         ...       ...       ...   ...  
94353  0.468748  0.015652  1.079288   pos  
94354  1.618014  0.562601  0.003662   pos  
94355  0.748404 -0.063100  0.856685   pos  
94356  1.805664 -0.195180 -0.121038   pos  
94357  0.032174 -0.009272  0.412247   pos  

[94358 rows x 11 columns]

In [45]:
cv_data_new = pd.DataFrame(cv_data_array)

In [46]:
np.array(data_labels.iloc[train_data_len:train_data_len+cv_data_len])

array(['neg', 'neg', 'neg', ..., 'neg', 'neg', 'neg'], dtype=object)

In [47]:
cv_data_new['class'] = np.array(data_labels.iloc[train_data_len:train_data_len+cv_data_len])

In [48]:
cv_data_new

0         1         2         3         4         5         6  \
0      4.375650 -1.923019  3.164612 -0.708693 -0.199780 -0.159363 -0.109625   
1      2.985500 -2.677008  4.604001  0.799445  1.882125 -0.631776 -1.279782   
2      5.951292  3.136198 -3.358095  0.395612  0.639854 -1.070951 -0.187051   
3     -2.777654  0.411677  0.143736 -0.805834  4.217130 -1.444873 -0.642637   
4      5.906019  2.960488 -3.538398  0.007898 -0.277291 -0.366160  0.181799   
...         ...       ...       ...       ...       ...       ...       ...   
11995 -4.491342  5.070792  2.887281  0.600429 -1.968078 -0.972848 -0.202327   
11996  3.847332 -3.044562  4.159467 -1.243965 -1.393246 -0.105707  1.363949   
11997  5.242754  1.373921 -1.242263  0.404229  0.870724 -0.868457 -0.576406   
11998 -3.884651  3.900302  1.880839 -0.347632 -2.625407 -0.322529  0.660955   
11999 -3.151485 -1.464693 -2.075731 -4.476525  1.313244  0.221068  1.205458   

              7         8         9 class  
0      0.698721  0.264161 -0.581026   neg  
1      0.769835  0.721953 -0.688407   neg  
2      0.393726  0.011674 -0.286622   neg  
3     -2.692433 -0.646653  1.098073   neg  
4     -0.176696 -0.137871 -0.304892   neg  
...         ...       ...       ...   ...  
11995  0.051638  0.213154  0.115508   neg  
11996 -0.553918 -0.662275  0.502632   neg  
11997  0.918963  1.207373 -1.075745   neg  
11998  0.702870  1.470849  0.831031   neg  
11999  0.160069  1.623903  0.500249   neg  

[12000 rows x 11 columns]

# Applying Gaussian Naive Bayes algorithm on training data 

In [49]:
from sklearn.naive_bayes import GaussianNB

In [50]:
gaussian_nb = GaussianNB()

In [51]:
train_data_new.shape

(94358, 11)

In [52]:
gaussian_nb.fit(X=np.array(train_data_new.iloc[:,0:train_data_new.shape[1]-1]),y=np.array(train_data_new['class']))

GaussianNB()

# Finally predicting the labels using CV data and calculating the accuracy

In [53]:
predicted_labels = gaussian_nb.predict(X=np.array(cv_data_new.iloc[:,0:cv_data_new.shape[1]-1]))

In [54]:
predicted_labels

array(['neg', 'neg', 'neg', ..., 'neg', 'neg', 'neg'], dtype='<U3')

In [55]:
from sklearn.metrics import classification_report

In [56]:
print(classification_report(y_true=np.array(cv_data_new['class']),y_pred=predicted_labels))

              precision    recall  f1-score   support

         neg       1.00      0.91      0.95     11821
         pos       0.13      0.92      0.23       179

    accuracy                           0.91     12000
   macro avg       0.57      0.91      0.59     12000
weighted avg       0.99      0.91      0.94     12000



# let's do it on test data

In [57]:
test_data_array

array([[ 5.14617941,  1.65996062, -1.67873999, ...,  1.04061726,
         0.55960601, -0.69592349],
       [ 5.46221194,  1.91146464, -2.03453645, ...,  1.1503976 ,
         0.89532841, -0.49901829],
       [-3.54520469,  1.60006889,  1.06323611, ..., -1.08506009,
        -0.64009735,  1.08501528],
       ...,
       [-4.12502188,  3.66760517,  1.83414115, ..., -0.13800253,
        -0.58152863, -1.27944563],
       [ 4.99443836, -0.42758154,  1.2913615 , ...,  0.78707815,
         0.90806587, -0.93292751],
       [ 5.99401737,  3.1341563 , -3.56624829, ...,  0.07838696,
         0.15714048,  0.16172464]])

In [58]:
predicted_labels_test = gaussian_nb.predict(X=test_data_array)

In [59]:
predicted_labels_test

array(['neg', 'neg', 'neg', ..., 'neg', 'neg', 'neg'], dtype='<U3')

In [60]:
print(classification_report(y_true=np.array(test_data['class']),y_pred=predicted_labels_test))

              precision    recall  f1-score   support

         neg       1.00      0.91      0.95     15625
         pos       0.20      0.93      0.33       375

    accuracy                           0.91     16000
   macro avg       0.60      0.92      0.64     16000
weighted avg       0.98      0.91      0.94     16000

